/*
 * Form principal de la Aplicacion. Mostraremos toda la parte importante del programa
 */
package ventana;

import database.CreateBBDD;
import database.Query;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class Incial extends javax.swing.JFrame {
    
    CreateBBDD dataBase = new CreateBBDD(); // clases con codigo
    Query query = new Query();
    
    FindFitment findFitment = new FindFitment(); // ventanas de Buscar
    FindSize findSize = new FindSize();
    FindMaterial findMaterial = new FindMaterial();
    
    AddFitment addFitment = new AddFitment(this); // ventanas de Añadir
    AddMaterial addMaterial = new AddMaterial(this);
    AddSize addSize = new AddSize(this);
    
    int row = 0; // fila pinchada con el raton
    int col = 0; // columna pinchada con el raton
    String edit = ""; // valor que edito
    int edit2 = 0;
    int id = 0; // valor que edito

    /**
     * Creates new form Incial
     */
    public Incial() {
        initComponents();
        dataBase.connect("muebles");
        query.tableFitment(jTableMuebles); // pongo os valores en las tablas
        query.tableSize(jTableTamanos);
        query.tableMaterial(jTableMateriales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMuebles = new javax.swing.JTable();
        jButtonAnadirMuebles = new javax.swing.JButton();
        jButtonEliminarMuebles = new javax.swing.JButton();
        jButtonEditarMuebles = new javax.swing.JButton();
        jButtonBuscarMuebles = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTamanos = new javax.swing.JTable();
        jButtonAnadirTamano = new javax.swing.JButton();
        jButtonEliminarTamano = new javax.swing.JButton();
        jButtonEditarTamano = new javax.swing.JButton();
        jButtonBuscarTamano = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jButtonAnadirMateriales = new javax.swing.JButton();
        jButtonEliminarMateriales = new javax.swing.JButton();
        jButtonEditarMateriales = new javax.swing.JButton();
        jButtonBuscarMateriales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Muebles");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        jTableMuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Nombre", "Precio", "Paquetes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMueblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMuebles);

        jButtonAnadirMuebles.setText("Añadir");
        jButtonAnadirMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirMueblesActionPerformed(evt);
            }
        });

        jButtonEliminarMuebles.setText("Eliminar");
        jButtonEliminarMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMueblesActionPerformed(evt);
            }
        });

        jButtonEditarMuebles.setText("Editar");
        jButtonEditarMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMueblesActionPerformed(evt);
            }
        });

        jButtonBuscarMuebles.setText("Buscar");
        jButtonBuscarMuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMueblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButtonEliminarMuebles)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarMuebles)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarMuebles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnadirMuebles)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadirMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Muebles", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        jTableTamanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ancho", "Fondo", "Altura", "Peso Balda", "Mueble"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTamanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTamanosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTamanos);

        jButtonAnadirTamano.setText("Añadir");
        jButtonAnadirTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirTamanoActionPerformed(evt);
            }
        });

        jButtonEliminarTamano.setText("Eliminar");
        jButtonEliminarTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTamanoActionPerformed(evt);
            }
        });

        jButtonEditarTamano.setText("Editar");
        jButtonEditarTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTamanoActionPerformed(evt);
            }
        });

        jButtonBuscarTamano.setText("Buscar");
        jButtonBuscarTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarTamanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jButtonEliminarTamano)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarTamano)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarTamano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnadirTamano)))
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadirTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tamaño", jInternalFrame2);

        jInternalFrame3.setVisible(true);

        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Principal", "Secundario", "Mueble"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMaterialesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableMateriales);

        jButtonAnadirMateriales.setText("Añadir");
        jButtonAnadirMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirMaterialesActionPerformed(evt);
            }
        });

        jButtonEliminarMateriales.setText("Eliminar");
        jButtonEliminarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMaterialesActionPerformed(evt);
            }
        });

        jButtonEditarMateriales.setText("Editar");
        jButtonEditarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMaterialesActionPerformed(evt);
            }
        });

        jButtonBuscarMateriales.setText("Buscar");
        jButtonBuscarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMaterialesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jButtonEliminarMateriales)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarMateriales)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarMateriales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnadirMateriales)))
                .addContainerGap())
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadirMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Materiales", jInternalFrame3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dataBase.disconnect(); // desconecta al cerrar la ventana
        this.dispose();
        Runtime.getRuntime().halt(0);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonBuscarMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMueblesActionPerformed
        findFitment.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarMueblesActionPerformed

    private void jButtonBuscarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarTamanoActionPerformed
        findSize.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarTamanoActionPerformed

    private void jButtonBuscarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMaterialesActionPerformed
        findMaterial.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarMaterialesActionPerformed

    private void jButtonAnadirMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirMueblesActionPerformed
        addFitment.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirMueblesActionPerformed

    private void jButtonAnadirTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirTamanoActionPerformed
        addSize.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirTamanoActionPerformed

    private void jButtonAnadirMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirMaterialesActionPerformed
       addMaterial.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirMaterialesActionPerformed

    private void jButtonEliminarMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMueblesActionPerformed
        query.deleteFitment(id);

        updateTableFitment(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEliminarMueblesActionPerformed

    private void jButtonEliminarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTamanoActionPerformed
        query.deleteSize(id);

        updateTableSize(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEliminarTamanoActionPerformed

    private void jButtonEliminarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMaterialesActionPerformed
        query.deleteMaterial(id);

        updateTableMaterial(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEliminarMaterialesActionPerformed

    private void jButtonEditarMueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMueblesActionPerformed
        if(jTableMuebles.isEditing()){ // comprueba si esta editando la tabla
            JOptionPane.showMessageDialog(null, "Deje de editar el campo (Pulse ENTER para dejar de editar).", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(col == 1){
                edit = (String) ((DefaultTableModel)jTableMuebles.getModel()).getValueAt(row, col);//cojo el valor editado
                query.updateFitment(col, edit, edit2, id); // paso los valores a la otra funcion
            }
            else{
                edit2 = (int) Integer.parseInt((String) ((DefaultTableModel)jTableMuebles.getModel()).getValueAt(row, col));//cojo el valor editado
                query.updateFitment(col, edit, edit2, id); // paso los valores a la otra funcion
            }
        }

        updateTableFitment(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEditarMueblesActionPerformed

    private void jButtonEditarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarTamanoActionPerformed
        if(jTableTamanos.isEditing()){ // comprueba si esta editando la tabla
            JOptionPane.showMessageDialog(null, "Deje de editar el campo (Pulse ENTER para dejar de editar).", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{          
            edit2 = (int) Integer.parseInt((String) ((DefaultTableModel)jTableTamanos.getModel()).getValueAt(row, col));//cojo el valor editado
            query.updateSize(col, edit2, id); // paso los valores a la otra funcion
        }

        updateTableFitment(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEditarTamanoActionPerformed

    private void jButtonEditarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMaterialesActionPerformed
        if(jTableMateriales.isEditing()){ // comprueba si esta editando la tabla
            JOptionPane.showMessageDialog(null, "Deje de editar el campo (Pulse ENTER para dejar de editar).", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(col == 1 || col == 2){
                edit = (String) ((DefaultTableModel)jTableMateriales.getModel()).getValueAt(row, col);//cojo el valor editado
                query.updateMaterial(col, edit, edit2, id); // paso los valores a la otra funcion
            }
            else{
                edit2 = (int) Integer.parseInt((String) ((DefaultTableModel)jTableMateriales.getModel()).getValueAt(row, col));//cojo el valor editado
                query.updateMaterial(col, edit, edit2, id); // paso los valores a la otra funcion
            }
        }

        updateTableFitment(); // actualizo los valores de la tabla
    }//GEN-LAST:event_jButtonEditarMaterialesActionPerformed

    private void jTableMueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMueblesMouseClicked
        JTable source = (JTable) evt.getSource();
        row = source.rowAtPoint(evt.getPoint()); // me devuelve la fila pinchada
        col = source.columnAtPoint(evt.getPoint());
        id = (int) source.getModel().getValueAt(row, 0);
    }//GEN-LAST:event_jTableMueblesMouseClicked

    private void jTableTamanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTamanosMouseClicked
        JTable source = (JTable) evt.getSource();
        row = source.rowAtPoint(evt.getPoint()); // me devuelve la fila pinchada
        col = source.columnAtPoint(evt.getPoint());
        id = (int) source.getModel().getValueAt(row, 0);
    }//GEN-LAST:event_jTableTamanosMouseClicked

    private void jTableMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialesMouseClicked
        JTable source = (JTable) evt.getSource();
        row = source.rowAtPoint(evt.getPoint()); // me devuelve la fila pinchada
        col = source.columnAtPoint(evt.getPoint());
        id = (int) source.getModel().getValueAt(row, 0);
    }//GEN-LAST:event_jTableMaterialesMouseClicked
    
    public void updateTableFitment(){ // actualizo la tabla
        while(jTableMuebles.getRowCount() != 0) ((DefaultTableModel)jTableMuebles.getModel()).removeRow(0); // consigue el total de columnas y las elimina
        
        query.tableFitment(jTableMuebles);
    }

    public void updateTableSize(){ // actualizo la tabla
        while(jTableTamanos.getRowCount() != 0) ((DefaultTableModel)jTableTamanos.getModel()).removeRow(0); // consigue el total de columnas y las elimina
        
        query.tableSize(jTableTamanos);
    }
    
    public void updateTableMaterial(){ // actualizo la tabla
        while(jTableMateriales.getRowCount() != 0) ((DefaultTableModel)jTableMateriales.getModel()).removeRow(0); // consigue el total de columnas y las elimina
        
        query.tableMaterial(jTableMateriales);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirMateriales;
    private javax.swing.JButton jButtonAnadirMuebles;
    private javax.swing.JButton jButtonAnadirTamano;
    private javax.swing.JButton jButtonBuscarMateriales;
    private javax.swing.JButton jButtonBuscarMuebles;
    private javax.swing.JButton jButtonBuscarTamano;
    private javax.swing.JButton jButtonEditarMateriales;
    private javax.swing.JButton jButtonEditarMuebles;
    private javax.swing.JButton jButtonEditarTamano;
    private javax.swing.JButton jButtonEliminarMateriales;
    private javax.swing.JButton jButtonEliminarMuebles;
    private javax.swing.JButton jButtonEliminarTamano;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JTable jTableMuebles;
    private javax.swing.JTable jTableTamanos;
    // End of variables declaration//GEN-END:variables
}
